# Generated by Django 5.2.8 on 2025-11-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, verbose_name='Modelo del Sensor')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('installation_date', models.DateField(verbose_name='Fecha de Instalación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('MAINTENANCE', 'Mantenimiento')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
