# Generated by Django 5.2.8 on 2025-11-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
