# Generated by Django 5.2.8 on 2025-12-09 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensor_options_alter_sensor_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('maintenance_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(verbose_name='Fecha del Mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción de actividades')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='maintenance_certificates/', verbose_name='Certificado de Calibración/Mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='sensors.sensor', verbose_name='Sensor')),
                ('technical_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsable')),
            ],
            options={
                'verbose_name': 'Bitácora de Mantenimiento',
                'verbose_name_plural': 'Bitácoras de Mantenimiento',
                'db_table': 'maintenance_log',
                'ordering': ['-log_date'],
            },
        ),
    ]
