# Generated by Django 5.2.8 on 2025-11-23 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Institución')),
                ('physic_address', models.CharField(max_length=255, verbose_name='Dirección Física')),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10, verbose_name='Estado de la Solicitud')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('review_comments', models.TextField(blank=True, verbose_name='Comentarios de Revisión')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_requests', to='institutions.environmentalinstitution', verbose_name='Institución Solicitante')),
                ('proposed_station_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_admin_requests', to=settings.AUTH_USER_MODEL, verbose_name='Administrador de Estación Propuesto')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionColorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(help_text='Formato hexadecimal, ej: #FF5733', max_length=7, verbose_name='Color Hex')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='institutions.environmentalinstitution', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Color de Institución',
                'unique_together': {('institution', 'color_hex')},
            },
        ),
    ]
