# Generated by Django 5.2.8 on 2025-11-23 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationrequest',
            name='proposed_station_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_admin_requests', to=settings.AUTH_USER_MODEL, verbose_name='Administrador de Estación Propuesto'),
        ),
        migrations.AddField(
            model_name='integrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterUniqueTogether(
            name='institutioncolorset',
            unique_together={('institution', 'color_hex')},
        ),
    ]
