# Generated by Django 5.2.8 on 2025-12-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalinstitution',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Validación'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20, verbose_name='Estado de Validación'),
        ),
        migrations.AlterField(
            model_name='integrationrequest',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Validación'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10, verbose_name='Estado de la Solicitud'),
        ),
    ]
