# Generated by Django 5.2.8 on 2025-12-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_environmentalinstitution_validation_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegrationRequest',
        ),
    ]
