# Generated by Django 5.2.8 on 2025-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='approved_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Validación'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20, verbose_name='Estado de Asignación'),
        ),
    ]
