# Generated by Django 5.2.8 on 2025-11-23 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Estación')),
                ('operative_status', models.CharField(choices=[('ACTIVE', 'Operativa'), ('MAINTENANCE', 'En Mantenimiento'), ('INACTIVE', 'Inactiva'), ('OFFLINE', 'Fuera de Línea')], default='INACTIVE', max_length=20, verbose_name='Estado Operativo')),
                ('authentication_token', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Token de Autenticación')),
                ('geographic_location_lat', models.FloatField(verbose_name='Latitud')),
                ('geographic_location_long', models.FloatField(verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='institutions.environmentalinstitution', verbose_name='Institución Propietaria')),
                ('manager_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stations', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Técnico (Manager)')),
            ],
            options={
                'verbose_name': 'Estación de Monitoreo',
                'verbose_name_plural': 'Estaciones de Monitoreo',
                'db_table': 'monitoring_station',
            },
        ),
    ]
