# Generated by Django 5.2.8 on 2025-12-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_delete_integrationrequest'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationAffiliationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Validación'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20, verbose_name='Estado de la Solicitud')),
                ('review_comments', models.TextField(blank=True, verbose_name='Comentarios de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affiliation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_requests', to='stations.monitoringstation', verbose_name='Estación Solicitante')),
                ('target_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_affiliation_requests', to='institutions.environmentalinstitution', verbose_name='Institución Destino')),
            ],
            options={
                'verbose_name': 'Solicitud de Afiliación',
                'verbose_name_plural': 'Solicitudes de Afiliación',
                'db_table': 'station_affiliation_request',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('station', 'target_institution'), name='unique_pending_affiliation_per_station')],
            },
        ),
    ]
