# Generated by Django 5.2.8 on 2025-12-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_stationaffiliationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringstation',
            name='address_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección o Referencia Física'),
        ),
    ]
