# Generated by Django 5.2.8 on 2025-12-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_monitoringstation_address_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringstation',
            name='operative_status',
            field=models.CharField(choices=[('ACTIVE', 'Operativa'), ('PENDING', 'Pendiente'), ('REJECTED', 'Rechazada'), ('MAINTENANCE', 'En Mantenimiento'), ('INACTIVE', 'Inactiva'), ('OFFLINE', 'Fuera de Línea')], default='INACTIVE', max_length=20, verbose_name='Estado Operativo'),
        ),
        migrations.DeleteModel(
            name='StationAffiliationRequest',
        ),
    ]
