# Generated by Django 5.2.8 on 2025-12-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_monitoringstation_operative_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringstation',
            name='operative_status',
            field=models.CharField(choices=[('ACTIVE', 'Operativa'), ('PENDING', 'Pendiente'), ('REJECTED', 'Rechazada'), ('MAINTENANCE', 'En Mantenimiento'), ('INACTIVE', 'Inactiva'), ('OFFLINE', 'Fuera de Línea')], default='PENDING', max_length=20, verbose_name='Estado Operativo'),
        ),
    ]
