# Generated by Django 5.2.8 on 2025-11-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableCatalog',
            fields=[
                ('variable_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre (Ej: Material Particulado 2.5)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código (Ej: PM2.5)')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad (Ej: µg/m³)')),
                ('min_expected_value', models.FloatField(default=0)),
                ('max_expected_value', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(verbose_name='Valor Medido')),
                ('measure_date', models.DateTimeField(verbose_name='Fecha de Toma de Dato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='sensors.sensor', verbose_name='Sensor Origen')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurements.variablecatalog')),
            ],
            options={
                'ordering': ['-measure_date'],
                'indexes': [models.Index(fields=['sensor', 'measure_date'], name='measurement_sensor__16350d_idx')],
            },
        ),
    ]
