# Generated by Django 5.2.8 on 2025-11-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-measure_date'], 'verbose_name': 'Medición', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='variablecatalog',
            options={'verbose_name': 'Catálogo de Variables', 'verbose_name_plural': 'Catálogos de Variables'},
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='measurement_sensor__1f3858_idx',
            old_name='measurement_sensor__16350d_idx',
        ),
        migrations.AlterModelTable(
            name='measurement',
            table='measurement',
        ),
        migrations.AlterModelTable(
            name='variablecatalog',
            table='variable_catalog',
        ),
    ]
